version: "3.9"
services:
  web:
    build: amazoniaweb
    environment: 
        - REACT_APP_API_PORT=${API_PORT}
        - REACT_APP_API_IP=${API_IP}
        - REACT_APP_CLIENT_ID=${GOOGLE_CLIENT_ID}
    ports:
      - "${VIEW_PORT}:${VIEW_PORT}"
  api:
    build: amazoniaweb-api
    environment: 
        - PORT=${API_PORT}
        - BRIDGE_PORT=${BRIDGE_PORT}
        - TOKEN_SECRET=${TOKEN_SECRET}
        - HYPERLEDGER_SERVICE_IP=hyperledger-brige
    ports:
        - "${API_PORT}:${API_PORT}"
    networks:
      - backend
  hyperledger-brige:
    build: hyperledger-register-service
    environment: 
        - PORT=${BRIDGE_PORT}
    ports:
        - "${BRIDGE_PORT}:${BRIDGE_PORT}"
    networks:
      - backend
networks:
  backend:
    driver: bridge