version: "3.3"
services:
  web:
    network_mode: "host"
    build: amazoniaweb
    environment: 
        - REACT_APP_API_PORT=${API_PORT}
        - REACT_APP_API_IP=${API_IP}
        - REACT_APP_CLIENT_ID=${GOOGLE_CLIENT_ID}
  api:
    network_mode: "host"
    build: amazoniaweb-api
    environment: 
        - PORT=${API_PORT}
        - BRIDGE_PORT=${BRIDGE_PORT}
        - TOKEN_SECRET=${TOKEN_SECRET}
        - HYPERLEDGER_SERVICE_IP=localhost
  hyperledger-brige:
    network_mode: "host"
    build: hyperledger-register-service
    environment: 
        - PORT=${BRIDGE_PORT}