version: "3.3"
services:
  web:
    network_mode: "host"
    build: amazoniaweb
    env_file:
      - web.env
  api:
    network_mode: "host"
    build: amazoniaweb-api
    env_file:
      - api.env
  hyperledger-bridge:
    network_mode: "host"
    build: hyperledger-register-service
    env_file:
      - bridge.env
